### ISSUE TITLE
建议发布 Releaes

### ISSUE THREAD

**Issue by Ad-closeNN** [upbingun233/MTimer#1]
如题，可能有的用户**不会**编译。建议直接把编译好的`.exe`文件发布在[Release 页面](https://github.com/upbingun233/MTimer/releases)，以便用户下载而无需编译即可使用。

**Comment by upbingun** [comment]
不行，该程序作为一个API使用，像java,lang.Object一样，不是用来运行的

**Comment by Ad-closeNN** [comment]
> 不行，该程序作为一个API使用，像java,lang.Object一样，不是用来运行的

哦知道了，行吧那关了吧
